### ISSUE TITLE
rest-firebase doesn't seem to see disconnects/downtime.

### ISSUE THREAD

**Issue by volksport** [CodementorIO/rest-firebase#8] opened 2016-01-11 22:01 UTC
Tested using:
rest-firebase 1.0.3
rest-core 3.5.92 & 3.5.91
httpclient 2.7.1 & 2.7.0.1

When a long running event source is disconnected (specifically I believe when the firebase server goes down for a few minutes -- some nodes do this! e.g. http://status.firebase.com/1363624 ) rest-firebase doesn't seem to realize it lost connection. I don't see any reconnection attempts, and so my daemon runs but is disconnected from firebase until I restart it.

Neither onerror and onreconnect are called (I log when they are).

I'm setting up the connection like this:

fb = RestFirebase.new(:site => ENV['FIREBASE_URL'],
:auth => ENV['FIREBASE_SECRET'],
:timeout => 7
)

**Comment by godfat** [comment] 2016-01-12 08:57
I think we were probably also hit by this because we often saw unsynchronized data, though we didn't log it therefore we have no idea.

To be honest, I am not very familiar with IO, and I can't seem to reproduce this. My guess is that this line in rest-core:

``` ruby
sock.readline("\n\n")
```

Didn't do anything when the socket was already disconnected under some circumstance. Since I can't reproduce I can only guess it. Can you see if this patch for rest-core would make thing better?

``` patch
diff --git a/lib/rest-core/event_source.rb b/lib/rest-core/event_source.rb
index 10850d6..b4d9f53 100644
--- a/lib/rest-core/event_source.rb
+++ b/lib/rest-core/event_source.rb
@@ -100,7 +100,7 @@ class RestCore::EventSource < Struct.new(:client, :path, :query, :opts,
   private
   # called in requesting thread after the request is done
   def onmessage_for sock
-    until sock.eof?
+    until sock.eof? || IO.select([sock], [], [], 30).nil?
       event = sock.readline("\n\n").split("\n").inject({}) do |r, i|
         k, v = i.split(': ', 2)
         r[k] = v
```

The idea is that we wait for readable event for the socket, timeout in 30 seconds. If there's no data from Firebase in 30 seconds, we close the connection on our side. If this works out, we could see how we could tweak the timeout. Firebase would send `keep-alive` event if there's no data around periodically. I can't seem to find how long they would send this event on their document though. Ideally our timeout should match that period.

Let me know if you have any thoughts. Thanks!

**Comment by volksport** [comment] 2016-01-14 19:35
While not conclusive, as pingdom didn't show any downtime -- it appears I got a reconnect last night with this patch. I will keep running and see if I can match up verified downtime with a reconnect.

```
» 13 Jan 2016 19:04:52.785 2016-01-14 00:04:52.483199+00:00 app disconnected.1 - - EOFError
» 13 Jan 2016 19:04:52.861 2016-01-14 00:04:52.483248+00:00 app disconnected.1 - - Reconnecting...
» 13 Jan 2016 19:04:55.092 2016-01-14 00:04:54.786210+00:00 app disconnected.1 - - Connection refused - connect(2) for "s-dal5-nss-28.firebaseio.com" port 443 (s-dal5-nss-28.firebaseio.com:443)
» 13 Jan 2016 19:04:55.168 2016-01-14 00:04:54.786221+00:00 app disconnected.1 - - Reconnecting...
» 13 Jan 2016 19:05:59.577 2016-01-14 00:05:59.275709+00:00 app disconnected.1 - - Connection Opening...
```

**Comment by godfat** [comment] 2016-01-15 08:06
That's certainly very helpful. Thank you!

I am wondering though, should we distinguish different exceptions?
Say, introduce a new RestCore::IOTimeout which extends from EOFError,
so that you'll have more idea was it timeout or really EOF?

Or perhaps some messages would be good enough.

**Comment by volksport** [comment] 2016-01-16 20:02
Pingdom claims 3 minutes of downtime yesterday, and I didn't see a disconnect, but also can't verify if it was still connected. Sadly my daily heroku restart was 4 minutes later. I'd like to keep watching, but now I'm not convinced it is fully working yet. Will update when I know more.

**Comment by godfat** [comment] 2016-01-17 12:37
Thank you for the update.

**Comment by volksport** [comment] 2016-01-17 23:08
Appears it in fact does not take care of a downtime situation.
Pingdom shows a 4m downtime at 18:31 on Jan 16, and my logs show the daemon stops receiving keep-alives and does not attempt to reconnect at the same time. Nothing else happens until the daily restart at 8:12 on Jan 17.

```
» 16 Jan 2016 18:29:57.544 2016-01-16 23:29:57.264906+00:00 app disconnected.1 - - keep-alive
» 16 Jan 2016 18:30:27.548 2016-01-16 23:30:27.265425+00:00 app disconnected.1 - - keep-alive
» 16 Jan 2016 18:30:57.544 2016-01-16 23:30:57.265354+00:00 app disconnected.1 - - keep-alive
» 17 Jan 2016 08:12:48.788 2016-01-17 13:12:48.396037+00:00 app disconnected.1 - - Starting...
» 17 Jan 2016 08:12:49.272 2016-01-17 13:12:48.879370+00:00 app disconnected.1 - - Connection Opening...
» 17 Jan 2016 08:12:49.257 2016-01-17 13:12:48.885085+00:00 app disconnected.1 - - Disconnect User:206
» 17 Jan 2016 08:12:49.364 2016-01-17 13:12:48.887863+00:00 app disconnected.1 - - Disconnect User:209
» 17 Jan 2016 08:13:19.421 2016-01-17 13:13:19.134333+00:00 app disconnected.1 - - keep-alive
```

**Comment by godfat** [comment] 2016-01-18 16:43
I am curious where this got stuck. Was it `sock.eof?`, or `sock.readline("\n\n")`?
Is it possible that you put the log around them so that we could know where it got stuck?

If it got stuck at `sock.eof?`, then perhaps we could remove it. If it got stuck at `sock.readline("\n\n")`... well, since we already put `IO.select` there, the only reason this got stuck might be missing "\n\n". For example, if Firebase kept the connection while never sending anything, then we could get stuck here forever. If this is the case, perhaps we would need to set another timeout. Unfortunately there's no timeout option for `readline`...

**Comment by datibbaw** [comment] 2016-01-22 12:35
Stumbled upon this conversation because I want to use this lib to replace our existing simple request based client, and leveraging a socket pool to reduce the number of SSL handshakes.

Just curious whether this issue would impact such an implementation as well or if I could manage it by specifying a lifetime of sockets ;-)

**Comment by godfat** [comment] 2016-01-22 13:10
Did you mean you want to use rest-firebase along with a customized socket pool?
The sockets used in rest-firebase are retrieved from https://github.com/nahi/httpclient
It should be responsible for keep-alive connections. (there's a connection pool in httpclient)

However, this issue is more about event stream -- which is different from regular REST API.
By using event stream, you basically keep the connection forever, so there's no point to use
any pool in this case.

**Comment by volksport** [comment] 2016-01-22 17:19
So I took a day or two to research httpclient and rest-core and my feeling is that this is a larger issue with how httpclient creates the connection and how TCP sockets operate. First, i believe httpclient disgards the write pipe and only passes along the read pipe. TCP sockets normally can't tell when a remote disconnects unless it sends a signal and won't know until they attempt a write. 

See where I'm going? When Firebase crashes/goes down it won't notify the remote connection, so we never know it closes. There might be some underlying things we can do like looking at some of the flags set on the TCP connection (but this is platform dependent), but IO doesn't offer them (whereas TCPSocket does). I'm also concerned about not having access to the write on the pipe.

I could be wrong about any/all of this. But I've also started using a modified version of https://github.com/firebase/EventSource-Examples/tree/master/ruby and I'm having good luck with it reconnecting (but haven't been able to 100% verify a reconnect after downtime, since Firebase all of a sudden is having less downtime...)

**Comment by godfat** [comment] 2016-01-22 17:33
Yes, I am aware that we might not be able to tell if the TCP socket disconnected without writing to it. That's why I am guessing that we should have some kind of external timeout to monitor this.

However, I think it's reasonable that httpclient didn't give us any write pipe, because for event stream, we're not going to write anything after the request has been sent. I am not sure if we could write anything.

On the other hand, `IO.select` on read pipe might not work well. I might need to check if there's a way to retrieve the underlying socket, instead of a read pipe. If we could really retrieve the socket, perhaps `IO.select` would be sufficient.

As for eventmachine, that's completely a different direction. Personally I won't put any further bet on eventmachine because it's kind of abandoned with good reasons.

I'll see if I could get the socket from httpclient. If not, perhaps I would try to use TCPSocket directly or net/http or some other HTTP client which could give us the socket. (Or try to give httpclient a patch in order to get the underlying sockets)

Thanks a lot for the investigation!

**Comment by volksport** [comment] 2016-01-22 18:04
If you are able to get socket options, this MAY prove useful: http://stackoverflow.com/a/959054

**Comment by godfat** [comment] 2016-01-22 19:25
Thanks for the reference. Hope this would work out.

**Comment by godfat** [comment] 2016-01-25 20:44
I haven't figured out how to get the socket from httpclient, nor did I figure out how other HTTP client could do this easily. Before going deeper, I decided to push a few more changes, removing the use of `IO#eof?` because it could probably hang. I also tried that `IO.select` did work for pipes.

I don't know if this could fix anything, but I think I should still try it. It would be great if you could try it out, too. Greatly appreciated.

It's lying on branch timeout-for-eventsource-socket in rest-core, referenced above.

**Comment by volksport** [comment] 2016-01-26 23:59
I changed the READ_WAIT to 35, since it's 30 +/- 1/2 second and it disconnects often when it's set to 30.

Then I ran it locally, and turned off my wifi (at 23:47:00), then reconnected my wifi (at 23:47:41). I've found this is as close of an approximation as I can get to firebase going down. The good news is it times out and reconnects. It's funny because I actually tried this same change awhile back but must not have tested it well enough. Wish I had before I went and wrote a second version of this with eventmachine.

I can't verify anything, but this may work. I'll see about trying to run this version for a bit in production.

You can likely guess where these log outputs are, but here's the repo: https://github.com/volksport/rest-core/blob/timeout-for-eventsource-socket/lib/rest-core/event_source.rb#L106

```
Disconn OK: Connection Opening... 2016-01-26 23:45:29.456
Inside onmessage_for loop 2016-01-26 23:45:29.457
Inside readline 2016-01-26 23:45:29.458
Inside readline 2016-01-26 23:45:29.459
Inside onmessage_for loop 2016-01-26 23:45:59.455
Inside readline 2016-01-26 23:45:59.455
Inside readline 2016-01-26 23:45:59.455
Disconn OK: keep-alive 2016-01-26 23:45:59.455
Inside onmessage_for loop 2016-01-26 23:46:29.598
Inside readline 2016-01-26 23:46:29.598
Inside readline 2016-01-26 23:46:29.598
Disconn OK: keep-alive 2016-01-26 23:46:29.598
Inside onmessage_for loop 2016-01-26 23:46:59.703
Inside readline 2016-01-26 23:46:59.704
Inside readline 2016-01-26 23:46:59.704
Disconn OK: keep-alive 2016-01-26 23:46:59.704
Disconn ERROR: EOFError EOFError 2016-01-26 23:47:34.740
Disconn ERROR: Reconnecting... 2016-01-26 23:47:35.741
Disconn ERROR: getaddrinfo: Name or service not known (xxxx.firebaseio.com:443) SocketError 2016-01-26 23:47:35.750
Disconn ERROR: Reconnecting... 2016-01-26 23:47:36.752
Disconn ERROR: getaddrinfo: Name or service not known (xxxx.firebaseio.com:443) SocketError 2016-01-26 23:47:36.757
Disconn ERROR: Reconnecting... 2016-01-26 23:47:37.758
Disconn ERROR: getaddrinfo: Name or service not known (xxxx.firebaseio.com:443) SocketError 2016-01-26 23:47:37.762
Disconn ERROR: Reconnecting... 2016-01-26 23:47:38.763
Disconn ERROR: getaddrinfo: Name or service not known (xxxx.firebaseio.com:443) SocketError 2016-01-26 23:47:38.768
Disconn ERROR: Reconnecting... 2016-01-26 23:47:39.769
Disconn ERROR: getaddrinfo: Name or service not known (xxxx.firebaseio.com:443) SocketError 2016-01-26 23:47:39.774
Disconn ERROR: Reconnecting... 2016-01-26 23:47:40.775
Disconn OK: Connection Opening... 2016-01-26 23:47:41.309
Inside onmessage_for loop 2016-01-26 23:47:41.311
Inside readline 2016-01-26 23:47:41.311
Inside readline 2016-01-26 23:47:41.311
Inside onmessage_for loop 2016-01-26 23:48:11.590
Inside readline 2016-01-26 23:48:11.590
Inside readline 2016-01-26 23:48:11.590
Disconn OK: keep-alive 2016-01-26 23:48:11.590
```

**Comment by godfat** [comment] 2016-01-27 12:29
Great, thank you! We could probably see that
Firebase would send keep-alive for every 30
seconds, and whenever we set it to 35 seconds,
it means if Firebase somehow delayed the event
for 5 seconds then we'll just reconnect it.

There should probably have an option for this
in the future.

So though we can't verify if this does fix the issue,
this should still somehow improve the situation and
reduce the chances of getting stuck.

I'll release a new version with this patch soon if there's
no further concern.

**Comment by godfat** [comment] 2016-01-27 13:26
I didn't intend to close this.

**Comment by volksport** [comment] 2016-02-03 07:17
After a great than 1 hour (ONE HOUR+?!) downtime tonight on ss-dal5-nss-28 http://status.firebase.com/1363624/2016/02 It seems the reconnect is working properly! But, I'd still like to point to my issue #9 which still makes my daemon unstable.

**Comment by godfat** [comment] 2016-02-03 07:26
Excellent, thank you very much!

p.s. I once thought Firebase could be a great data store, however given that it's not as stable as I would expect, and it doesn't seem to scale nicely, now I think it's still a great messaging channel, but should not be used as the main data store at all.

**Closed** 2016-07-12 17:16 UTC
